# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs: 
- job: Calculate_WF_Jira_Issues
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Calculate_WF/Calculate_WF_Jira_Issues
                    development
                    compression,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;svn,Common/Keys;svn,Windows/Calculate.Windows/Src;shared-base,null;shared-windows,null;democommon-windows,null;svn,Windows/XlsIO.Windows/Src;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;spellchecker-base,null;pdf,null;svn,Base/ExcelToPdfConverter.Base/Src;tools-windows,null;syncfusion-core,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: Calculate_WF_Jira_Issues
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: CalculateWF
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Calculate_WF/CalculateWF
                    development
                    compression,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;svn,Common/Keys;svn,Windows/Calculate.Windows/Src;shared-base,null;shared-windows,null;democommon-windows,null;svn,Windows/XlsIO.Windows/Src;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;spellchecker-base,null;pdf,null;svn,Base/ExcelToPdfConverter.Base/Src;tools-windows,null;syncfusion-core,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: CalculateWF
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

