# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs:
- job: DigitalGauge
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Gauge_WF/DigitalGauge
                    development
                    shared-base,null;gauge-windows,null;shared-windows,null;democommon-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;grouping-base,null;grid-grouping-windows,null;spellchecker-base,null;tools-windows,null' 
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DigitalGauge
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: LinearGauge
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Gauge_WF/LinearGauge
                    development
                    shared-base,null;gauge-windows,null;shared-windows,null;democommon-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;grouping-base,null;grid-grouping-windows,null;spellchecker-base,null;tools-windows,null' 
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: LinearGauge
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true 

- job: RadialGauge
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Gauge_WF/RadialGauge 
                    development
                    shared-base,null;gauge-windows,null;shared-windows,null;democommon-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;grouping-base,null;grid-grouping-windows,null;spellchecker-base,null;tools-windows,null' 
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: RadialGauge
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

