# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs:
- job: XpTaskbar
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/XpTaskbar 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Chart.Base/Src;svn,Base/Diagram.Base/Src;svn,Windows/Diagram.Windows/Src;svn,Windows/Grouping.Windows/Src;grid-grouping-windows,null;syncfusion-core,null;chart-winforms,null;spellchecker-base,null;tools-windows,null;edit-windows,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: XpTaskbar
        
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

