# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs:
- job: DockingManagerEight
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerEight
                    development
                    shared-base,null;shared-windows,null;democommon-windows,null;grid-windows,null;spellchecker-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;tools-windows,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerEight

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: DockingManagerFive
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerFive 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Diagram.Base/Src;svn,Windows/Diagram.Windows/Src;svn,Base/Chart.Base/Src;svn,Windows/Grouping.Windows/Src;svn,Base/Linq.Base/Src;grid-grouping-windows,null;chart-winforms,null;syncfusion-core,null;compression,null;barcode,null;pdf,null;officechart,null;docio,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;
                    gridconverter-windows,null;spellchecker-base,null;tools-windows,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerFive

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: DockingManagerFour
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerFour 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Diagram.Base/Src;svn,Windows/Diagram.Windows/Src;svn,Base/Chart.Base/Src;svn,Base/Scripting.Base/Src;svn,Windows/Grouping.Windows/Src;svn,Base/MIME.Base/Src;grid-grouping-windows,null;chart-winforms,null;syncfusion-core,null;compression,null;calculate,null;spellchecker-base,null;tools-windows,null;edit-windows,null;svn,Windows/Scripting.Windows/Src;htmlui-windows,null' 
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerFour

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: DockingManagerNine
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerNine 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Chart.Base/Src;svn,Windows/Grouping.Windows/Src;grid-grouping-windows,null;chart-winforms,null;syncfusion-core,null;spellchecker-base,null;tools-windows,null;schedule-base,null;schedule-windows,null;edit-windows,null'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerNine

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: DockingManagerOne
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerOne
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Scripting.Base/Src;svn,Base/MIME.Base/Src;htmlui-windows,null;spellchecker-base,null;tools-windows,null;edit-windows,null;syncfusion-core,null;svn,Windows/Scripting.Windows/Src'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerOne

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      

- job: DockingManagerSeven 
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerSeven 
                    development
                    shared-base,null;shared-windows,null;democommon-windows,null;grid-windows,null;spellchecker-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;tools-windows,null;syncfusion-core,null'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerSeven

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true 

- job: DockingManagerSix
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerSix 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Chart.Base/Src;svn,Base/Linq.Base/Src;grid-grouping-windows,null;chart-winforms,null;syncfusion-core,null;compression,null;barcode,null;pdf,null;officechart,null;docio,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;gridconverter-windows,null;spellchecker-base,null;tools-windows,null;edit-windows,null'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerSix

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

- job: DockingManagerThree 
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerThree 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Diagram.Base/Src;svn,Windows/Diagram.Windows/Src;svn,Base/Scripting.Base/Src;svn,Base/MIME.Base/Src;syncfusion-core,null;htmlui-windows,null;spellchecker-base,null;tools-windows,null;svn,Windows/Scripting.Windows/Src'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerThree
        
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true 

- job: DockingManagerTwo 
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingManagerTwo 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Scripting.Base/Src;svn,Base/Linq.Base/Src;svn,Base/MIME.Base/Src;grid-grouping-windows,null;syncfusion-core,null;compression,null;barcode,null;pdf,null;officechart,null;docio,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;htmlui-windows,null;spellchecker-base,null;tools-windows,null;edit-windows,null;svn,Windows/Scripting.Windows/Src' 
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingManagerTwo

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true 

- job: DockingPackage
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1280'
        height: '1024'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WF/DockingPackage 
                    development
                    shared-base,null;democommon-windows,null;shared-windows,null;grid-windows,null;grouping-base,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Diagram.Base/Src;svn,Windows/Diagram.Windows/Src;svn,Base/Chart.Base/Src;svn,Base/Scripting.Base/Src;svn,Base/Linq.Base/Src;svn,Windows/Grouping.Windows/Src;grid-grouping-windows,null;chart-winforms,null;syncfusion-core,null;compression,null;barcode,null;pdf,null;officechart,null;docio,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;gridconverter-windows,null;spellchecker-base,null;tools-windows,null;pivotanalysis-windows,null;edit-windows,null;gridhelperclasses-windows,null;svn,Windows/PDF.Windows/Src;svn,Windows/XlsIO.Windows/Src;svn,Windows/DocIO.Windows/Src;svn,Base/DLS.Base/Src'
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: DockingPackage

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true

