# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

jobs:
- job: comboboxadv
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1920'
        height: '1080'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WPF/comboboxadv 
                    development 
                    shared-wpf,WPF-834393-The-ArgumentException-was-thrown-when-selecting-an-item-from-the-ComboBoxAdv;tools-wpf,null;sfinput-xaml,null;propertygrid-wpf,null;sfshared-xaml,null;syncfusion-core,null;svn,Common/Keys;svn,WPF/Shared.MVVM.WPF/Src;data-xaml,null;datagrid-xaml,null;compression,null;barcode,null;pdf,null;officechart,null;docio,null;calculate,null;pivotanalysis-base,null;compoundfile,null;odf,null;xlsio,null;sfchart-xaml,null;svn,WPF/Chart.WPF/Src;gridcommon-xaml,null;charttoimageconvertor,null;spreadsheet-xaml,null;spreadsheethelper-xaml,null;sfbusyindicator-xaml,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: comboboxadv

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true
