# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

jobs:
- job: editcontrol   
  timeoutInMinutes: 0
  pool:
     name: "Desktop-xaml-winforms-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1920'
        height: '1080'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TrunkAutomation/Tools_WPF/editcontrol 
                    development 
                    shared-wpf,null;tools-wpf,null;gridcommon-xaml,null;edit-wpf,WPF-827446-Dark-theme-support-in-edit-control;syncfusion-core,null;data-xaml,null;datagrid-xaml,null;svn,Common/Keys;svn,Base/Linq.Base/Src;grid-wpf,null;sfinput-xaml,null;propertygrid-wpf,null;sfshared-xaml,null;sfradialmenu-xaml,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: editcontrol
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true       