# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs:
- job: PivotGrid_JIRA_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/PivotGrid_WF/PivotGrid_JIRA_2019
                    development
                    shared-base,null;shared-windows,null;grouping-base,null;grid-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;tools-windows,null;svn,Base/Chart.Base/Src;chart-winforms,null;pivotanalysis-base,null;pivotchart-windows,null;pivotanalysis-windows,null;compression,null;officechart,null;docio,null;xlsio,null;svn,Windows/XlsIO.Windows/Src;pivotconverter-windows,null'
    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: PivotGrid_JIRA_2019
        
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true        