# ASP.NET Core (.NET Framework) 
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

jobs:
- job: GGC_Jira_MT_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Grid_WF/GGC_Jira_MT_2019
                    development
                    compression,null;officechart,null;docio,null;svn,Common/Keys;svn,Base/Grid.Base/Src;shared-base,null;shared-windows,null;grouping-base,null;grid-windows,null;svn,Base/Grid.Grouping.Base/Src;grid-grouping-windows,null;compoundfile,null;odf,null;xlsio,null;svn,Common/Keys;svn,Windows/Calculate.Windows/Src;democommon-windows,null;svn,Base/Tools.Base/Src;spellchecker-base,null;tools-windows,null;gauge-windows,null;svn,Base/Chart.Base/Src/;chart-winforms,null;pdf,null;pivotanalysis-base,null;svn,Base/Linq.Base/Src;pivotanalysis-windows,
                    null
                    false' 

  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: GGC_Jira_MT_2019

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      

- job: GridControl_Jira_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Grid_WF/GridControl_Jira_2019 
                    development
                    compression,null;officechart,null;docio,null;shared-base,null;gauge-windows,null;shared-windows,null;democommon-windows,null;compoundfile,null;odf,null;xlsio,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Grid.Grouping.Base/Src;svn,Base/Tools.Base/Src;grid-windows,null;grouping-base,null;grid-grouping-windows,null;spellchecker-base,null;svn,Windows/Grouping.Windows/Src;tools-windows,null;syncfusion-core,null;edit-windows,null;svn,Base/Chart.Base/Src;chart-winforms,null;pdf,null;pivotanalysis-base,null;svn,Base/Linq.Base/Src;pivotanalysis-windows,null;gridconverter-windows,null;gridhelperclasses-windows,null'

  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: GridControl_Jira_2019

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      

- job: GridGrouping_Jira_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Grid_WF/GridGrouping_Jira_2019 
                    development
                    shared-base,null;shared-windows,null;democommon-windows,null;grouping-base,null;schedule-base,null;grid-windows,null;grid-grouping-windows,null;svn,Common/Keys;svn,Base/Grid.Base/Src;svn,Base/Tools.Base/Src;tools-windows,null;svn,Base/Chart.Base/Src;chart-winforms,null;gridconverter-windows,null;pivotanalysis-windows,null;schedule-windows,null;gridhelperclasses-windows,
                    null
                    false'

  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: GridGrouping_Jira_2019

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      

- job: GridGroupingControl_Jira_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Grid_WF/GridGroupingControl_Jira_2019 
                    development
                    compression,null;officechart,null;docio,null;svn,Base/Grid.Base/Src;shared-base,null;shared-windows,null;grouping-base,null;grid-windows,null;svn,Base/Grid.Grouping.Base/Src;grid-grouping-windows,null;compoundfile,null;odf,null;xlsio,null;svn,Common/Keys;svn,Windows/Calculate.Windows/Src;democommon-windows,null;svn,Base/Tools.Base/Src;spellchecker-base,null;tools-windows,null;gauge-windows,null;svn,Base/Chart.Base/Src/;svn,chart-winforms,null;pdf,null;pivotanalysis-base,null;svn,Base/Linq.Base/Src;pivotanalysis-windows,
                    null
                    false'

  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: GridGroupingControl_Jira_2019

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      

- job: WF_CR_2019
  timeoutInMinutes: 0
  pool:
    name: "Desktop-xaml-vmss"

  steps:
  - task: ScreenResolutionUtility@1
    inputs:
        displaySettings: 'specific'
        width: '1366'
        height: '768'

  - task: CmdLine@1
    inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net6.0\'
        arguments: 'https://svn.syncfusion.com/svn/studio/Source/Testing/Automation/TestCases_Automation/TestStudioAutomation/Grid_WF/WF_CR_2019 
                    development
                    compression,null;officechart,null;docio,null;svn,Common/Keys;svn,Base/Grid.Base/Src;shared-base,null;shared-windows,null;grouping-base,null;grid-windows,null;svn,Base/Grid.Grouping.Base/Src;grid-grouping-windows,null;compoundfile,null;odf,null;xlsio,null;calculate,null;svn,Windows/Calculate.Windows/Src;democommon-windows,null;svn,Base/Tools.Base/Src;spellchecker-base,null;tools-windows,null;gauge-windows,null;svn,Base/Chart.Base/Src/;chart-winforms,null;pdf,null;pivotanalysis-base,null;svn,Base/Linq.Base/Src;pivotanalysis-windows,null'    
                    
  - task: PublishBuildArtifacts@1
    inputs:
        pathtoPublish: 'D:\AutomationReports\'
        ArtifactName: WF_CR_2019

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'D:\AutomationReports'
      Contents: '**/*'
      RemoveSourceFolder: true      
